### ISSUE TITLE
Windows系统、使用Visual Studio 2022编译Debug版本出错

### ISSUE THREAD

**Issue by chnykn** [Tencent/tgfx#378]
Windows系统、使用Visual Studio 2022编译Debug版本出错。具体如下：

1、CMake产生工Visual Studio 2022程文件
  使用x64 Native Tools Command Prompt for VS 2022，在win目录执行
  cmake -G "Visual Studio 17 2022" -A x64 -B ./build-x64

2、打开 build-x64 目录下的Hello2D.sln，编译Debug版本，Hello2D项目出错，错误信息如下
mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in TGFXWindow.obj
mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in TGFXWindow.obj

![err](https://github.com/user-attachments/assets/fa9dd5bf-5a52-4f4f-95aa-c3100060fa6b)

==========
环境如下
  操作系统：Windows 11 家庭中文版， 23H2
  开发工具：Visual Studio 2022 Community ，17.12.3
  TGFX版本：今日（2024.12.14）最新（main分支）

另外：Release正常，RelWithDebug也正常 且 可以调试。所以，Debug编译不过，也不影响调试。

=========
看了看代码，写的很牛，大佬厉害！！

**Comment by domchen** [comment]
Fixed in #383  感谢反馈，这个问题是因为CMake设计成了一次只能有一种编译类型的系统，而VS是多配置的系统，同时存在Debug 和 Release的时候，这里就会有一些冲突。CMake项目内有第三方库编译需要依赖这个标志进行判断，默认不做指定的情况下就会强制让第三方库按Release编译，所以就出现你遇到的问题。简单的解法就是生成VS工程的时候，再一个`-DCMAKE_CONFIGURATION_TYPES="Debug"` 参数指定只生成一个编译类型的工程即可。README 里的相关文档也已经更新。另外这是从CMAKE生成VS工程都会有的问题，如果正常使用CMAKE进行开发是不会有问题的，比如用CLion打开win目录下的工程。
